### ISSUE TITLE
Angular Universal - Module build failed

### ISSUE THREAD

**Issue by stephanegg** [JPeer264/ngx-tooltip-server#1]
Hi, 

When using angular universal, the compilation fails. Could you package the lib using the Angular Package Format (https://goo.gl/jB3GVv) ? 

![screen shot 2018-01-07 at 03 55 48](https://user-images.githubusercontent.com/31510240/34646066-f207d108-f35e-11e7-9e9e-550ed89fb6dc.png)

Thanks

**Comment by JPeer264** [comment]
Hey, thanks for your issue.

Sure, I can try it tonight. Also a PR would be appreciated.

**Comment by JPeer264** [comment]
@stephanegg can you give v`1.1.0` a try? Hope it works 👍

**Comment by JPeer264** [comment]
If the error still exist, please feel free to reopen this issue 👍  (Closed due to no response)

**Comment by stephanegg** [comment]
It works with 1.1.0, thank you @JPeer264.
