### ISSUE TITLE
Package.json incorrectly specifies ES5 vs ES6 modules

### ISSUE THREAD

**Issue by mikejf-pr** [JPeer264/ngx-tooltip-server#3]
Per the angular package specification, "ES2015" should specify the ES2015 compiled module and "module" should specify the ES5 module. This package currently is the other way around, which is breaking our ES5-requiring tools when we use it.

**Comment by JPeer264** [comment]
Thanks for your issue.

Oh, that is my bad. You have any idea how this can be solved? A PR is appreciated.

**Comment by mikejf-pr** [comment]
Just swapping the two in package.json should do it, no?

**Comment by JPeer264** [comment]
@mikejf-pr it is ok. I will do it, as I will now let `ng-packagr` manage all this.

**Comment by JPeer264** [comment]
Should be fixed in `v1.1.1`
